apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: request-validator-pod
  labels:
    app: request-validator
spec:
  containers:
  - name: request-validator
    image: us-central1-docker.pkg.dev/percy-k8s-csci5709/kubernetes-registry/request_validator:latest
    volumeMounts:
    - name: data-volume
      mountPath: "/Pratik_PV_dir/"
    ports:
    - containerPort: 6000
      hostPort: 6000
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: shared-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: request-validator
spec:
  selector:
    app: request-validator
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-pod1-communication
spec:
  podSelector:
    matchLabels:
      app: request-validator
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: sum-producer
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: sum-producer